//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTouch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Extensions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Extensions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KTouch.Properties.Extensions", typeof(Extensions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .avi.
        /// </summary>
        public static string AVI {
            get {
                return ResourceManager.GetString("AVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dir.
        /// </summary>
        public static string DIR {
            get {
                return ResourceManager.GetString("DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gif.
        /// </summary>
        public static string GIF {
            get {
                return ResourceManager.GetString("GIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg.
        /// </summary>
        public static string JPG {
            get {
                return ResourceManager.GetString("JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mp4.
        /// </summary>
        public static string MP4 {
            get {
                return ResourceManager.GetString("MP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpg.
        /// </summary>
        public static string MPG {
            get {
                return ResourceManager.GetString("MPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        public static string PNG {
            get {
                return ResourceManager.GetString("PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .wmv.
        /// </summary>
        public static string WMV {
            get {
                return ResourceManager.GetString("WMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xps.
        /// </summary>
        public static string XPS {
            get {
                return ResourceManager.GetString("XPS", resourceCulture);
            }
        }
    }
}
